require 'test/unit'

require 'rubygems'
require 'active_support'
require 'active_support/core_ext'
require 'active_support/builder'
require 'active_support/xml_mini'
require 'active_support/test_case'
require 'active_model'
require 'active_model/errors'
require 'active_model/validations'
require 'active_model/serialization'

require File.dirname(__FILE__) + '/../init'
require File.dirname(__FILE__) + '/passenger'
require File.dirname(__FILE__) + '/car'